# Generated by Django 5.0.2 on 2024-03-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description1', models.TextField()),
                ('description2', models.TextField(blank=True, null=True)),
                ('description3', models.TextField(blank=True, null=True)),
                ('description4', models.TextField(blank=True, null=True)),
                ('description5', models.TextField(blank=True, null=True)),
                ('description6', models.TextField(blank=True, null=True)),
                ('description7', models.TextField(blank=True, null=True)),
                ('description8', models.TextField(blank=True, null=True)),
                ('description9', models.TextField(blank=True, null=True)),
                ('description10', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.CharField(choices=[('rings', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum'), ('bronze', 'Bronze'), ('other', 'Other')], default='rings', max_length=19)),
                ('img_uploaded', models.ImageField(null=True, upload_to='shop_photos/')),
            ],
        ),
    ]
