# Generated by Django 5.0.2 on 2024-03-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_type_alter_shop_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
